version: '3'
services:
  aspnetapp:
    build:
      context: .
      dockerfile: ./CryptoApp/Dockerfile
    ports:
      - "5555:80"
    depends_on:
      - reactapp

  reactapp:
    build:
      context: .
      dockerfile: ./cryptoapp-web/Dockerfile
    ports:
      - "3333:80"
